import { catalogId, nowIso } from "@/lib/utils";
import type {
  EquipmentType,
  Exercise,
  MovementPattern,
  MuscleGroup,
  TrackingType,
} from "./schema";

type Row = [
  slugN: number,
  name: string,
  primary: MuscleGroup,
  secondary: MuscleGroup[],
  equipment: EquipmentType,
  pattern: MovementPattern,
  tracking?: TrackingType,
];

const ROWS: Row[] = [
  [1, "Back Squat", "quadriceps", ["glutes", "hamstrings", "spinal_erectors"], "barbell", "squat"],
  [2, "Pause Back Squat", "quadriceps", ["glutes", "hamstrings", "spinal_erectors"], "barbell", "squat"],
  [3, "Front Squat", "quadriceps", ["glutes", "upper_back", "abdominals"], "barbell", "squat"],
  [4, "Box Squat", "quadriceps", ["glutes", "hamstrings"], "barbell", "squat"],
  [5, "Conventional Deadlift", "hamstrings", ["glutes", "spinal_erectors", "lats", "traps", "quadriceps", "forearms"], "barbell", "hinge"],
  [6, "Sumo Deadlift", "glutes", ["quadriceps", "hamstrings", "adductors", "spinal_erectors", "traps"], "barbell", "hinge"],
  [7, "Romanian Deadlift", "hamstrings", ["glutes", "spinal_erectors"], "barbell", "hinge"],
  [8, "Stiff-Leg Deadlift", "hamstrings", ["glutes", "spinal_erectors"], "barbell", "hinge"],
  [9, "Deficit Deadlift", "hamstrings", ["glutes", "spinal_erectors", "quadriceps"], "barbell", "hinge"],
  [10, "Rack Pull", "spinal_erectors", ["traps", "glutes", "forearms"], "barbell", "hinge"],
  [11, "Good Morning", "hamstrings", ["spinal_erectors", "glutes"], "barbell", "hinge"],
  [12, "Barbell Hip Thrust", "glutes", ["hamstrings", "quadriceps"], "barbell", "hinge"],
  [13, "Barbell Bench Press", "chest", ["front_delts", "triceps"], "barbell", "push"],
  [14, "Pause Bench Press", "chest", ["front_delts", "triceps"], "barbell", "push"],
  [15, "Close-Grip Bench Press", "triceps", ["chest", "front_delts"], "barbell", "push"],
  [16, "Incline Bench Press", "chest", ["front_delts", "triceps"], "barbell", "push"],
  [17, "Floor Press", "chest", ["triceps", "front_delts"], "barbell", "push"],
  [18, "Overhead Press", "front_delts", ["triceps", "traps", "abdominals"], "barbell", "push"],
  [19, "Push Press", "front_delts", ["triceps", "quadriceps", "traps"], "barbell", "push"],
  [20, "Pendlay Row", "lats", ["upper_back", "biceps", "spinal_erectors"], "barbell", "pull"],
  [21, "Bent-Over Row", "lats", ["upper_back", "biceps", "spinal_erectors"], "barbell", "pull"],
  [22, "Yates Row", "lats", ["upper_back", "biceps"], "barbell", "pull"],
  [23, "Barbell Shrug", "traps", ["forearms"], "barbell", "isolation"],
  [24, "Barbell Curl", "biceps", ["forearms"], "barbell", "isolation"],
  [25, "Barbell Lunge", "quadriceps", ["glutes", "hamstrings"], "barbell", "squat"],
  [26, "Barbell Bulgarian Split Squat", "quadriceps", ["glutes", "hamstrings"], "barbell", "squat"],
  [27, "Barbell Calf Raise", "calves", [], "barbell", "isolation"],
  [28, "JM Press", "triceps", ["chest"], "barbell", "isolation"],
  [29, "Dumbbell Bench Press", "chest", ["front_delts", "triceps"], "dumbbell", "push"],
  [30, "Dumbbell Incline Press", "chest", ["front_delts", "triceps"], "dumbbell", "push"],
  [31, "Dumbbell Overhead Press", "front_delts", ["triceps", "side_delts"], "dumbbell", "push"],
  [32, "Dumbbell Row", "lats", ["upper_back", "biceps"], "dumbbell", "pull"],
  [33, "Dumbbell Romanian Deadlift", "hamstrings", ["glutes", "forearms"], "dumbbell", "hinge"],
  [34, "Goblet Squat", "quadriceps", ["glutes", "abdominals"], "dumbbell", "squat"],
  [35, "Dumbbell Lunge", "quadriceps", ["glutes", "hamstrings"], "dumbbell", "squat"],
  [36, "Dumbbell Bulgarian Split Squat", "quadriceps", ["glutes", "hamstrings"], "dumbbell", "squat"],
  [37, "Dumbbell Curl", "biceps", ["forearms"], "dumbbell", "isolation"],
  [38, "Hammer Curl", "biceps", ["forearms"], "dumbbell", "isolation"],
  [39, "Dumbbell Lateral Raise", "side_delts", ["traps"], "dumbbell", "isolation"],
  [40, "Dumbbell Fly", "chest", ["front_delts"], "dumbbell", "isolation"],
  [41, "Dumbbell Pullover", "lats", ["chest", "triceps"], "dumbbell", "pull"],
  [42, "Dumbbell Shrug", "traps", ["forearms"], "dumbbell", "isolation"],
  [43, "Farmer Carry", "forearms", ["traps", "abdominals", "glutes"], "dumbbell", "carry", "distance_time"],
  [44, "Lat Pulldown", "lats", ["biceps", "upper_back"], "cable", "pull"],
  [45, "Seated Cable Row", "lats", ["upper_back", "biceps"], "cable", "pull"],
  [46, "Face Pull", "rear_delts", ["upper_back", "traps"], "cable", "pull"],
  [47, "Cable Fly", "chest", ["front_delts"], "cable", "isolation"],
  [48, "Tricep Pushdown", "triceps", [], "cable", "isolation"],
  [49, "Cable Curl", "biceps", ["forearms"], "cable", "isolation"],
  [50, "Cable Lateral Raise", "side_delts", [], "cable", "isolation"],
  [51, "Pallof Press", "obliques", ["abdominals"], "cable", "isolation"],
  [52, "Straight-Arm Pulldown", "lats", ["triceps"], "cable", "pull"],
  [53, "Leg Press", "quadriceps", ["glutes", "hamstrings"], "machine", "squat"],
  [54, "Hack Squat", "quadriceps", ["glutes"], "machine", "squat"],
  [55, "Leg Extension", "quadriceps", [], "machine", "isolation"],
  [56, "Lying Leg Curl", "hamstrings", [], "machine", "isolation"],
  [57, "Seated Leg Curl", "hamstrings", [], "machine", "isolation"],
  [58, "Chest Press Machine", "chest", ["front_delts", "triceps"], "machine", "push"],
  [59, "Shoulder Press Machine", "front_delts", ["triceps"], "machine", "push"],
  [60, "Pec Deck", "chest", ["front_delts"], "machine", "isolation"],
  [61, "Seated Row Machine", "lats", ["upper_back", "biceps"], "machine", "pull"],
  [62, "Calf Raise Machine", "calves", [], "machine", "isolation"],
  [63, "Hip Abduction Machine", "glutes", [], "machine", "isolation"],
  [64, "Hip Adduction Machine", "adductors", [], "machine", "isolation"],
  [65, "Pull-Up", "lats", ["biceps", "upper_back"], "bodyweight", "pull"],
  [66, "Chin-Up", "lats", ["biceps", "upper_back"], "bodyweight", "pull"],
  [67, "Dip", "chest", ["triceps", "front_delts"], "bodyweight", "push"],
  [68, "Push-Up", "chest", ["triceps", "front_delts", "abdominals"], "bodyweight", "push"],
  [69, "Nordic Hamstring Curl", "hamstrings", ["glutes"], "bodyweight", "hinge"],
  [70, "Hanging Leg Raise", "abdominals", ["obliques"], "bodyweight", "isolation"],
  [71, "Plank", "abdominals", ["obliques"], "bodyweight", "isolation", "duration"],
  [72, "Ab Wheel Rollout", "abdominals", ["lats"], "bodyweight", "isolation"],
  [73, "Inverted Row", "upper_back", ["lats", "biceps"], "bodyweight", "pull"],
  [74, "Pistol Squat", "quadriceps", ["glutes", "hamstrings"], "bodyweight", "squat"],
  [75, "Trap Bar Deadlift", "quadriceps", ["glutes", "hamstrings", "traps", "forearms"], "specialty_bar", "hinge"],
  [76, "Safety Bar Squat", "quadriceps", ["glutes", "upper_back", "spinal_erectors"], "specialty_bar", "squat"],
  [77, "Swiss Bar Bench Press", "chest", ["triceps", "front_delts"], "specialty_bar", "push"],
  [78, "Skull Crusher", "triceps", [], "barbell", "isolation"],
  [79, "Barbell Hip Hinge Shrug", "traps", ["spinal_erectors"], "barbell", "isolation"],
  [80, "Suitcase Carry", "obliques", ["forearms", "abdominals"], "dumbbell", "carry", "distance_time"],
];

export const EX = Object.fromEntries(ROWS.map(([n]) => [n, catalogId(n)])) as Record<number, string>;

export function starterExercises(): Exercise[] {
  const stamp = nowIso();
  return ROWS.map(([n, name, primary, secondary, equipment, pattern, tracking]) => ({
    id: catalogId(n),
    name,
    primaryMuscleGroup: primary,
    secondaryMuscleGroups: secondary,
    equipmentType: equipment,
    movementPattern: pattern,
    trackingType: tracking ?? "weight_reps",
    isCustom: false,
    isArchived: false,
    notes: "",
    createdAt: stamp,
    updatedAt: stamp,
  }));
}

export function findCatalogByName(name: string): Exercise | undefined {
  const key = name.trim().toLowerCase();
  return starterExercises().find((e) => e.name.toLowerCase() === key);
}
