/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAnalyticsRouteImport } from './routes/_app/analytics'
import { Route as AppBiometricsRouteImport } from './routes/_app/biometrics'
import { Route as AppEcosystemRouteImport } from './routes/_app/ecosystem'
import { Route as AppExercisesRouteImport } from './routes/_app/exercises'
import { Route as AppHardwareRouteImport } from './routes/_app/hardware'
import { Route as AppImportRouteImport } from './routes/_app/import'
import { Route as AppLogbookRouteImport } from './routes/_app/logbook'
import { Route as AppRoutinesRouteImport } from './routes/_app/routines'
import { Route as AppSessionRouteImport } from './routes/_app/session'
import { Route as AppSystemRouteImport } from './routes/_app/system'
import { Route as AppVaultRouteImport } from './routes/_app/vault'
import { Route as AppLogbookIdRouteImport } from './routes/_app/logbook_.$id'
import { Route as AppRoutinesIdRouteImport } from './routes/_app/routines_.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppBiometricsRoute = AppBiometricsRouteImport.update({
  id: '/biometrics',
  path: '/biometrics',
  getParentRoute: () => AppRoute,
} as any)
const AppEcosystemRoute = AppEcosystemRouteImport.update({
  id: '/ecosystem',
  path: '/ecosystem',
  getParentRoute: () => AppRoute,
} as any)
const AppExercisesRoute = AppExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => AppRoute,
} as any)
const AppHardwareRoute = AppHardwareRouteImport.update({
  id: '/hardware',
  path: '/hardware',
  getParentRoute: () => AppRoute,
} as any)
const AppImportRoute = AppImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppRoute,
} as any)
const AppLogbookRoute = AppLogbookRouteImport.update({
  id: '/logbook',
  path: '/logbook',
  getParentRoute: () => AppRoute,
} as any)
const AppRoutinesRoute = AppRoutinesRouteImport.update({
  id: '/routines',
  path: '/routines',
  getParentRoute: () => AppRoute,
} as any)
const AppSessionRoute = AppSessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => AppRoute,
} as any)
const AppSystemRoute = AppSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AppRoute,
} as any)
const AppVaultRoute = AppVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => AppRoute,
} as any)
const AppLogbookIdRoute = AppLogbookIdRouteImport.update({
  id: '/logbook_/$id',
  path: '/logbook/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppRoutinesIdRoute = AppRoutinesIdRouteImport.update({
  id: '/routines_/$id',
  path: '/routines/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/analytics': typeof AppAnalyticsRoute
  '/biometrics': typeof AppBiometricsRoute
  '/ecosystem': typeof AppEcosystemRoute
  '/exercises': typeof AppExercisesRoute
  '/hardware': typeof AppHardwareRoute
  '/import': typeof AppImportRoute
  '/logbook': typeof AppLogbookRoute
  '/routines': typeof AppRoutinesRoute
  '/session': typeof AppSessionRoute
  '/system': typeof AppSystemRoute
  '/vault': typeof AppVaultRoute
  '/logbook/$id': typeof AppLogbookIdRoute
  '/routines/$id': typeof AppRoutinesIdRoute
}
export interface FileRoutesByTo {
  '/analytics': typeof AppAnalyticsRoute
  '/biometrics': typeof AppBiometricsRoute
  '/ecosystem': typeof AppEcosystemRoute
  '/exercises': typeof AppExercisesRoute
  '/hardware': typeof AppHardwareRoute
  '/import': typeof AppImportRoute
  '/logbook': typeof AppLogbookRoute
  '/routines': typeof AppRoutinesRoute
  '/session': typeof AppSessionRoute
  '/system': typeof AppSystemRoute
  '/vault': typeof AppVaultRoute
  '/': typeof AppIndexRoute
  '/logbook/$id': typeof AppLogbookIdRoute
  '/routines/$id': typeof AppRoutinesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/biometrics': typeof AppBiometricsRoute
  '/_app/ecosystem': typeof AppEcosystemRoute
  '/_app/exercises': typeof AppExercisesRoute
  '/_app/hardware': typeof AppHardwareRoute
  '/_app/import': typeof AppImportRoute
  '/_app/logbook': typeof AppLogbookRoute
  '/_app/routines': typeof AppRoutinesRoute
  '/_app/session': typeof AppSessionRoute
  '/_app/system': typeof AppSystemRoute
  '/_app/vault': typeof AppVaultRoute
  '/_app/': typeof AppIndexRoute
  '/_app/logbook_/$id': typeof AppLogbookIdRoute
  '/_app/routines_/$id': typeof AppRoutinesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/biometrics'
    | '/ecosystem'
    | '/exercises'
    | '/hardware'
    | '/import'
    | '/logbook'
    | '/routines'
    | '/session'
    | '/system'
    | '/vault'
    | '/logbook/$id'
    | '/routines/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/analytics'
    | '/biometrics'
    | '/ecosystem'
    | '/exercises'
    | '/hardware'
    | '/import'
    | '/logbook'
    | '/routines'
    | '/session'
    | '/system'
    | '/vault'
    | '/'
    | '/logbook/$id'
    | '/routines/$id'
  id:
    | '__root__'
    | '/_app'
    | '/_app/analytics'
    | '/_app/biometrics'
    | '/_app/ecosystem'
    | '/_app/exercises'
    | '/_app/hardware'
    | '/_app/import'
    | '/_app/logbook'
    | '/_app/routines'
    | '/_app/session'
    | '/_app/system'
    | '/_app/vault'
    | '/_app/'
    | '/_app/logbook_/$id'
    | '/_app/routines_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/biometrics': {
      id: '/_app/biometrics'
      path: '/biometrics'
      fullPath: '/biometrics'
      preLoaderRoute: typeof AppBiometricsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ecosystem': {
      id: '/_app/ecosystem'
      path: '/ecosystem'
      fullPath: '/ecosystem'
      preLoaderRoute: typeof AppEcosystemRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/exercises': {
      id: '/_app/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof AppExercisesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/hardware': {
      id: '/_app/hardware'
      path: '/hardware'
      fullPath: '/hardware'
      preLoaderRoute: typeof AppHardwareRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/import': {
      id: '/_app/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof AppImportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/logbook': {
      id: '/_app/logbook'
      path: '/logbook'
      fullPath: '/logbook'
      preLoaderRoute: typeof AppLogbookRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/routines': {
      id: '/_app/routines'
      path: '/routines'
      fullPath: '/routines'
      preLoaderRoute: typeof AppRoutinesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/session': {
      id: '/_app/session'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof AppSessionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/system': {
      id: '/_app/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof AppSystemRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vault': {
      id: '/_app/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof AppVaultRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/logbook_/$id': {
      id: '/_app/logbook_/$id'
      path: '/logbook/$id'
      fullPath: '/logbook/$id'
      preLoaderRoute: typeof AppLogbookIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/routines_/$id': {
      id: '/_app/routines_/$id'
      path: '/routines/$id'
      fullPath: '/routines/$id'
      preLoaderRoute: typeof AppRoutinesIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppBiometricsRoute: typeof AppBiometricsRoute
  AppEcosystemRoute: typeof AppEcosystemRoute
  AppExercisesRoute: typeof AppExercisesRoute
  AppHardwareRoute: typeof AppHardwareRoute
  AppImportRoute: typeof AppImportRoute
  AppLogbookRoute: typeof AppLogbookRoute
  AppRoutinesRoute: typeof AppRoutinesRoute
  AppSessionRoute: typeof AppSessionRoute
  AppSystemRoute: typeof AppSystemRoute
  AppVaultRoute: typeof AppVaultRoute
  AppIndexRoute: typeof AppIndexRoute
  AppLogbookIdRoute: typeof AppLogbookIdRoute
  AppRoutinesIdRoute: typeof AppRoutinesIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppBiometricsRoute: AppBiometricsRoute,
  AppEcosystemRoute: AppEcosystemRoute,
  AppExercisesRoute: AppExercisesRoute,
  AppHardwareRoute: AppHardwareRoute,
  AppImportRoute: AppImportRoute,
  AppLogbookRoute: AppLogbookRoute,
  AppRoutinesRoute: AppRoutinesRoute,
  AppSessionRoute: AppSessionRoute,
  AppSystemRoute: AppSystemRoute,
  AppVaultRoute: AppVaultRoute,
  AppIndexRoute: AppIndexRoute,
  AppLogbookIdRoute: AppLogbookIdRoute,
  AppRoutinesIdRoute: AppRoutinesIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
